#!/bin/bash
read p c

func_tion() {

     for pathname in "$1"/*; do
        if [ -d "$pathname" ]; then
            func_tion "$pathname"
        else
            case "$pathname" in
                *.$c)
                    printf '%s\n' "$pathname"
            esac
        fi
    done
}

func_tion "$p"
