#!/bin/bash
read p c

func_tion() {

     for path in "$1"/*; do
        if [ -d "$path" ]; then
            func_tion "$path"
        else
            case "$path" in
                *.$c)
                    printf '%s\n' "$path"
            esac
        fi
    done
}

func_tion "$p"
